config/routes.rb
Rails.application.routes.draw do

  root 'main_pages#index'

  get 'contact' => 'main_pages#contact'

  get 'about' => 'main_pages#about'

  get 'help' => 'main_pages#help'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
 
  resources :users

  resources :books do 
    resources :data
  end
  

end

app/models/books.rb
class Books
  include Cequel::Record

  key :isbn, :text
  column :title, :text
  column :author, :text
  column :genre, :text
  column :publisher, :text
  set :tags, :text
  column :data, :blob
  
end

app/models/user.rb
require 'digest/sha1'

class User
  include Cequel::Record
  
  before_save { self.email = email.downcase }

  before_save :hash_password
  after_save :clear_password
  
  validate :password_same
  
  attr_accessor :password
  attr_accessor :password_confirmation
  
  key :username, :text, :index => true
  column :email, :text
  column :password_digest, :text
  column :first_name, :text
  column :last_name, :text
  column :salt, :text
  
  EMAIL_VALIDATE_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  
  validates :username, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: EMAIL_VALIDATE_REGEX }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :password_confirmation, presence: true, length: { minimum: 6 },
            allow_nil: true
  
  
  def authenticate(string='')
    string = BCrypt::Engine.hash_secret(string, self.salt)
    if string == self.password_digest
      return true
    else
      return false
    end
  end
  
  def User.find_by(value)
    begin
      self.find_by_username(value)
    rescue
      return nil
    end
  end
  
  private
  def password_same
    if password != password_confirmation
      errors.add(:password_confirmation, "Password do not match")
    end
  end
  
  private
  def hash_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password_digest = BCrypt::Engine.hash_secret(password, salt)
    end
  end
  
  def clear_password
    self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books = Books.all
  end
  
  def show
    @book = Books.find_by_isbn(params[:id])
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
    @book = Books.find_by_isbn(params[:book_id])
  end 
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
    # login
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email or password entered.'
      render new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to out Book Store"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Updated Profile"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password,
                                           :password_confirmation,
                                           :first_name, :last_name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def no_title(title = '')
    base_title = "Book Store"
    if title.empty?
      base_title
    else
      title + " | " + base_title
    end
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:username] = user.username
  end

  def current_user
    @current_user ||= User.find_by(session[:username])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:username)
    @current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/data.html.erb
<% provide(:title, @book.title) %>

<div class="book_data">
  <%= @book.data %>
</div>

app/views/books/index.html.erb
<% provide(:title, 'All Books') %>
<h1>All Books</h1>

<ul class="users">
  <% @books.each do |book| %>
  <li>
    <%= book.title %>
    <%= link_to book.isbn, book %>
  </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>

<div class="row center">
  <aside class="col-md-4">
    <section class="book_info">
      <h1>
	Title: <%= @book.title %>
      </h1>
      <%= link_to "Like", '#' %>
      <h2>
	Genre: <%= @book.genre %>
	<br />
	Author: <%= @book.author %>
	<br />
	Tags: 
	<% @book.tags.each do |tag| %>
	<%= tag %>
	<br />
	<% end %>
	<br />
	Publisher: <%= @book.publisher %>
	<br />
      </h2>
      <%= link_to "Read Book", book_data_path(@book) %>
    </section>
  </aside>
</div>

app/views/data/index.html.erb
<div class="book_data">
  <%= @book.data %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A Demo Book Store Web App
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar narbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Book Store", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Help", help_path %></li>
	<% if logged_in? %>
	<li><%= link_to "Users", users_path %></li>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	   Account <b class="caret"></b>
	  </a>
	  <ul class="dropdown-menu">
	    <li><%= link_to "Profile", current_user %></li>
	    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	    <li class="divider"></li>
	    <li>
	      <%= link_to "Log out", logout_path, method: "delete" %>
	    </li>
	  </ul>
	</li>
	<% else %>
	<li><%= link_to "Log In", login_path %></li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shiv.html.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html15.min.js>
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= no_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shiv' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/main_pages/about.html.erb
<% provide(:title, "About") %>

<h1>MainPages#about</h1>
<p>Find me in app/views/main_pages/about.html.erb</p>

app/views/main_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>MainPages#contact</h1>
<p>Find me in app/views/main_pages/contact.html.erb</p>

app/views/main_pages/help.html.erb
<% provide(:title, "Help" ) %>

<h1>MainPages#help</h1>
<p>Find me in app/views/main_pages/help.html.erb</p>

app/views/main_pages/index.html.erb
<div class="main center">
  <h1>Welcome to our Book Store!</h1>

  <h2>
    This is the home page for our demo app.
  </h2>
  <% if logged_in? %>
  <%= link_to "Books", books_path %>
  <% else %>
  <%= link_to "Sign up!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form has <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |err| %>
    <li><%= err %></li>
    <% end %> 
  </ul>
</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.submit "Save", class: "bun btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= user.first_name %>
    <%= user.last_name %>
    <%= link_to user.username, user %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'  %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
    
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
	Welcome <%= @user.first_name %> <%= @user.last_name %>.
      </h1>
    </section>
  </aside>
</div>